name: shopease
region: fra

domains:
  - domain: clinicbb.com
    type: PRIMARY
    zone: clinicbb.com

ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /api
    - component:
        name: frontend
      match:
        path:
          prefix: /admin
    - component:
        name: frontend
      match:
        path:
          prefix: /

services:
  - name: api
    github:
      repo: Basartemiz/e_commerce_cite
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    build_command: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      python manage.py create_admin_user
      python manage.py load_sample_products
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2
    envs:
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: core.settings
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "False"
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: clinicbb.com,www.clinicbb.com,${APP_DOMAIN},.ondigitalocean.app
      - key: CORS_ALLOWED_ORIGINS
        scope: RUN_AND_BUILD_TIME
        value: https://clinicbb.com,https://www.clinicbb.com,https://${APP_DOMAIN}
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}

static_sites:
  - name: frontend
    github:
      repo: Basartemiz/e_commerce_cite
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    catchall_document: index.html
    error_document: index.html
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: https://${APP_DOMAIN}/api

databases:
  - name: db
    engine: PG
    production: false
