name: shopease
region: nyc

services:
  # Django Backend API
  - name: api
    github:
      repo: Basartemiz/e-commerce-cite
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /api
    build_command: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ALLOWED_HOSTS
        value: "clinicbb.com,www.clinicbb.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://clinicbb.com,https://www.clinicbb.com"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"

# Static Frontend Site
static_sites:
  - name: frontend
    github:
      repo: Basartemiz/e-commerce-cite
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: "https://clinicbb.com/api"

# Managed PostgreSQL Database
databases:
  - name: db
    engine: PG
    production: false
    cluster_name: shopease-db
    db_name: shopease
    db_user: shopease_user
